export const FETCH_MATCH_COMMENTARIES_REQUEST =
  'FETCH_MATCH_COMMENTARIES_REQUEST';
export const FETCH_MATCH_COMMENTARIES_SUCCESS =
  'FETCH_MATCH_COMMENTARIES_SUCCESS';
export const FETCH_MATCH_COMMENTARIES_FAILURE =
  'FETCH_MATCH_COMMENTARIES_FAILURE';
