export const FETCH_COMPETITION_STANDINGS_REQUEST =
  'FETCH_COMPETITION_STANDINGS_REQUEST';
export const FETCH_COMPETITION_STANDINGS_SUCCESS =
  'FETCH_COMPETITION_STANDINGS_SUCCESS';
export const FETCH_COMPETITION_STANDINGS_FAILURE =
  'FETCH_COMPETITION_STANDINGS_FAILURE';
