export const GET_COMPETITIONS_REQUEST = 'GET_COMPETITIONS_REQUEST';
export const GET_COMPETITIONS_SUCCESS = 'GET_COMPETITIONS_SUCCESS';
export const GET_COMPETITIONS_FAILURE = 'GET_COMPETITIONS_FAILURE';
